### ISSUE TITLE
[11.0][web_widget_datepicker_options] When I try print a report in Invoicing an error occurs

### ISSUE THREAD

**Issue by yaniaular** [Vauxoo/web#19]
### Steps to reproduce:
Invoicing -> Reports -> Trial Balance

![error cuando intento imprimir un reporte](https://user-images.githubusercontent.com/7602170/41171772-5a696efc-6b17-11e8-92a5-7071aa91d855.png)

``` python
Error:
Uncaught TypeError: Cannot read property 'type' of undefined

https://test.inteco.org/web/content/329345-88c7a85/web.assets_backend.js:2947
Rastreo de error:
TypeError: Cannot read property 'type' of undefined
    at Class.init (https://test.inteco.org/web/content/329345-88c7a85/web.assets_backend.js:2947:274)
    at Class.init (https://test.inteco.org/web/content/250201-584d50c/web.assets_common.js:3819:371)
    at new Class (https://test.inteco.org/web/content/250201-584d50c/web.assets_common.js:3817:65)
    at HTMLDivElement.<anonymous> (https://test.inteco.org/web/content/329345-88c7a85/web.assets_backend.js:2879:1042)
    at Function.each (https://test.inteco.org/web/content/250201-584d50c/web.assets_common.js:625:767)
    at jQuery.fn.init.each (https://test.inteco.org/web/content/250201-584d50c/web.assets_common.js:613:643)
    at Class.render_searchview_buttons (https://test.inteco.org/web/content/329345-88c7a85/web.assets_backend.js:2879:987)
    at Class.render (https://test.inteco.org/web/content/329345-88c7a85/web.assets_backend.js:2879:588)
    at Array.<anonymous> (https://test.inteco.org/web/content/329345-88c7a85/web.assets_backend.js:2878:385)
    at Array.<anonymous> (https://test.inteco.org/web/content/250201-584d50c/web.assets_common.js:802:681)
```

## Solution

``` diff
--- a/web_widget_datepicker_options/static/src/js/datepicker.js
+++ b/web_widget_datepicker_options/static/src/js/datepicker.js
@@ -11,6 +11,7 @@ odoo.define('web_widget_datepicker_options.datepicker', function(require) {
             this._super.apply(this, arguments);
             var parent = this.getParent();
             if(typeof parent !== 'undefined'
+                && typeof parent.field !== 'undefined'
                     && parent.field.type === 'date'
                     && parent.nodeOptions){
                 var datepicker = parent.nodeOptions.datepicker;
@@ -24,6 +25,7 @@ odoo.define('web_widget_datepicker_options.datepicker', function(require) {
             this._super.apply(this, arguments);
             var parent = this.getParent();
             if(typeof parent !== 'undefined'
+                && typeof parent.field !== 'undefined'
                     && parent.field.type === 'datetime'
                     && parent.nodeOptions){
                 var datepicker = parent.nodeOptions.datepicker;
```

**Comment by yaniaular** [comment]
CC @luisg123v could you help me with a PR?
